export const CommonConstants = {
  EMAIL_FIELD : 'email',
  TASKS_FIELD : 'tasks',
  USER_COLLECTION : 'users',
  TASKS_COLLECTION : 'tasks',
  TASKS_USER_ID_FIELD : 'userId',
  TASK_ID_FIELD : 'id',
  INTERNAL_SERVER_ERROR : 500,
  INTERNAL_SERVER_ERROR_MSG : 'Algo ha salido mal!',
  VALIDATION_FAILED : 'Validation failed',
  STATUS_OK : 'success',
  STATUS_ERROR : 'error',
  SUCCESS_MESSAGE_DEFAULT : 'Operación exitosa',
  FIELD_NOT_DEFINED: undefined,
  NOT_DEFINED_USER: 'notDefined',
}