export const CommonConstants = {
  AUTH_LOCAL_STORAGE_KEY : 'atomTodoUser',
  EMPTY_OBJ_STR : '{}',
  EMPTY_STR: '',
  EMPTY_OBJ: null,
  INITIAL_OBJ: {},
  EMPTY_TASK: null,
  FALSE_VALUE: false,
  TRUE_VALUE: true,
  ZERO: 0,
  NOT_DEFINED_USER: 'notDefined',
  ID_USER_QUERY_PARAM: '?id=',
  MODAL_EDIT_TASK_TITLE: 'Editar tarea',
  MODAL_CREATE_TASK_TITLE: 'Nueva tarea',
  STATE_PENDING: 'PENDING',
  STATE_COMPLETED: 'COMPLETED',
  STATE_COMPLETED_MSG: 'Completado',
  STATE_PENDING_MSG: 'Pendiente',
  SUCCESS_RESPONSE: 'success',
  UPDATE_SUCCESSFUL_MSG: 'Tarea editada con éxito',
  INSERT_SUCCESSFUL_MSG: 'Tarea creada con éxito',
  REGISTER_SUCCESSFUL_MSG: 'Se ha creado el usuario correctamente',
  DELETE_TASK_SUCCESSFUL_MSG: 'Se ha eliminado la tarea',
  UPDATE_STATE_TASK_SUCCESSFUL_MSG: 'Se ha cambiado el estado de la tarea',
}